- db/sql/updates/updateTo3.2.0.sql
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainCatalogController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainInventoryController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemElementController.java
- src/java/CdbWebPortal/web/WEB-INF/web.xml
- src/java/CdbWebPortal/web/templates/errorViewTemplate.xhtml
- src/java/CdbWebPortal/web/views/common/private/commonChildListActionButtons.xhtml
- src/java/CdbWebPortal/web/views/common/private/commonChildListTreeTableActionButtons.xhtml
- src/java/CdbWebPortal/web/views/item/private/templates/itemListCustomizeDisplayDialogTemplate.xhtml
- src/java/CdbWebPortal/web/views/item/private/templates/itemListDataTableTemplateBase.xhtml
- src/java/CdbWebPortal/web/views/itemDomainInventory/private/itemDomainInventoryItemElementList.xhtml
- src/java/CdbWebPortal/web/views/itemElement/private/itemElementListActionButtons.xhtml
- src/java/CdbWebPortal/web/views/itemElement/private/itemElementListCustomizeDisplayDialogBase.xhtml
- src/java/CdbWebPortal/web/views/itemElement/private/itemElementTreeListActionButtons.xhtml
- src/java/CdbWebPortal/web/views/itemElement/private/templates/itemElementListObjectTemplate.xhtml
- src/java/CdbWebPortal/web/views/itemElement/private/templates/itemElementListTemplate.xhtml
Add functionality to display model number in item element list. 
Automatically reload filters on item pages based on a setting. 
Fix the browser back button interaction. 
Hide the private directories.
display appropriate error pages.
> New functionality & bug fixes

- tools/developer_tools/cdb_plugins/plugins/irmisLocation/java/irmisLocation.properties
- tools/developer_tools/cdb_plugins/plugins/irmisLocation/java/irmisLocationPluginManager.java
- tools/developer_tools/cdb_plugins/plugins/irmisLocation/java/irmisLocationPropertyTypeHandler.java
> A new plugin to add IRMIS location as a property.

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainLocationController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/PropertyTypeController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/EntityInfo.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ItemElement.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ListTbl.java
- src/java/CdbWebPortal/web/views/item/private/templates/itemListDataTableRowExpansionObjectTemplate.xhtml
- src/java/CdbWebPortal/web/views/item/private/templates/itemListObjectTemplate.xhtml
- src/java/CdbWebPortal/web/views/item/private/templates/itemViewTemplateBase.xhtml
- src/java/CdbWebPortal/web/views/itemDomainInventory/view.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemLocationSelectDialog.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemLocationSelection.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemViewPanelGridObject.xhtml
- src/java/CdbWebPortal/web/views/propertyValue/private/propertyValueDomainEntityCustomizeColumn.xhtml
> Performance improvements

- db/sql/static/populate_domain.sql
- db/sql/static/populate_setting_type.sql
- db/sql/updates/updateTo3.6.0.sql
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/settings/ItemDomainMachineDesignSettings.java
- src/java/CdbWebPortal/web/views/item/private/templateDefaults/itemListObjectColumns/itemItemIdentifier1.xhtml
- src/java/CdbWebPortal/web/views/item/private/templates/itemListObjectTemplate.xhtml
- src/java/CdbWebPortal/web/views/item/private/templates/itemListViewObjectTemplate.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignListObject.xhtml
> Add alternate name to machine design

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/CdbDomainEntityController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMAARCController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/utilities/GalleryUtility.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/utilities/StorageUtility.java
- src/java/CdbWebPortal/web/views/item/private/templates/itemViewTemplateBase.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMAARC/private/itemDomainMAARCViewable.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMAARC/view.xhtml
- src/java/CdbWebPortal/web/views/propertyValue/private/propertyValueListObjectValue.xhtml
- tools/developer_tools/cdb_plugins/plugins/dm/java/DmPropertyTypeHandler.java
> Add functionality for MAARC viewable file preview and gallery. 

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainInventoryController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainLocationController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/LocatableItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/Item.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ItemElement.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ItemElementHistory.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/LocatableItem.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/utilities/ItemElementUtility.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/utilities/ItemUtility.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/view/objects/LocationHistoryObject.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/entities/ItemLocationInformation.java
- src/java/CdbWebPortal/web/views/itemDomainLocation/private/itemDomainLocationTreeObject.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemLocationDetailsEditObject.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemLocationEditPanelGrid.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemLocationHistoryDialog.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemLocationSelection.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemViewPanelGridObject.xhtml
Closes #111 
Closes #247 
Closes #244
> Add functionality for locating inventory items in assembly and machine design

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/web/resources/css/portal.css
- src/java/CdbWebPortal/web/views/itemSource/private/itemSourceAddDialog.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/itemSourceEditListDataTable.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/itemSourceList.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/itemSourceListDataTable.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/itemSourceListObject.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourceContactInfo.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourceCost.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourceDescription.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourceManufacturer.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourceName.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourcePartNumber.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourceURL.xhtml
- src/java/CdbWebPortal/web/views/itemSource/private/templateDefaults/itemSourceFieldEditValues/itemSourceVendor.xhtml
> Add support for editing item source in view

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/beans/ItemDomainMachineDesignFacade.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/utilities/SearchResult.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/entities/ItemDomainCatalogSearchResult.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/entities/ItemDomainMdSearchResult.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/entities/ItemSearchResults.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/routes/ItemRoute.java
> Add search machine design api.

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/list.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignAutoScrollTreeTable.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewTreeList.xhtml
> Focus to machine design in list instead of going to view detail page. 

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/PropertyValueController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/view/jsf/utilities/FacesUtility.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerController.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/api/TravelerApi.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/objects/Form.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/objects/FormContent.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/objects/Label.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/objects/ReleasedForm.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/objects/ReleasedForms.java
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerBinderAddDialog.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerInstanceCreateConfiguration.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateAddDialog.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateArchiveListDialog.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateLinkDialog.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateList.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateListObject.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateReleasedVersionSelectionColumn.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateReleasedVersionSelectionDataTable.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateUpdatePrefVersionDialog.xhtml
> Support released travelers functionality.

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/Item.java
- src/java/CdbWebPortal/web/resources/css/portal.css
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/list.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewTreeList.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignListObject.xhtml
> Support favorites in md

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/view/objects/KeyValueObject.java
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignCreateFromTemplateEditPanelGrid.xhtml
> Allow creation of machine design from template hiearchically.

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/list.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewTreeList.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignKeyboardShortcutDialog.xhtml
> Add expand/collapse all functionality for machine design. 

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/LocatableItemController.java
- src/java/CdbWebPortal/web/views/itemDomainInventory/private/componentInventoryViewPanelGrid.xhtml
- src/java/CdbWebPortal/web/views/itemDomainInventory/private/itemDomainInventoryBillOfMaterialsEditPanel.xhtml
- src/java/CdbWebPortal/web/views/itemDomainInventory/private/templateDefaults/itemFieldEditValues/itemDomainInventoryStatus.xhtml
- src/java/CdbWebPortal/web/views/locatableItem/private/locatableItemViewPanelGridObject.xhtml
> Misc dev issues.

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ItemElement.java
- src/java/CdbWebPortal/web/resources/css/portal.css
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/list.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignAutoScrollTreeTable.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewTreeList.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignKeyboardShortcutDialog.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/templates/itemDomainMachineDesignTreeTableTemplate.xhtml
> Add md search

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ItemDomainMachineDesign.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/LocatableItem.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/PropertyValue.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/PropertyValueHistory.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/view/objects/LocationHistoryObject.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/entities/ItemHierarchy.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/entities/ItemLocationInformation.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/routes/ItemRoute.java
> Show location history from API.

- src/java/CdbWebPortal/web/resources/css/portal.css
- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerController.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerDomainInventoryController.java
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerInstanceObjectProgress.xhtml
> Add completed bar

- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerController.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerDomainCatalogController.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/view/objects/CreatedFromTemplateSummaryObject.java
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateList.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateListDataTable.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerTemplateTravelerListDialog.xhtml
> Show travelers created from a template. 

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/CdbEntityController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/LoginController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/beans/UserInfoFacade.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/Item.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ItemElement.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/UserInfo.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/utilities/EntityInfoUtility.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/entities/NewLocationInformation.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/routes/DomainRoute.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/rest/routes/ItemRoute.java
> Allow creation of location from API

- tools/developer_tools/python-client/CdbApiFactory.py
> Add the new domain api.

- db/sql/static/populate_allowed_entity_type_domain.sql
- db/sql/static/populate_entity_type.sql
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/constants/EntityTypeName.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainInventoryController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/beans/ItemDomainMachineDesignFacade.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/beans/ItemFacadeBase.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/Item.java
- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/model/db/entities/ItemDomainMachineDesign.java
- src/java/CdbWebPortal/web/views/itemDomainInventory/private/itemDomainInventoryListDataTableRowExpansion.xhtml
- src/java/CdbWebPortal/web/views/itemDomainInventory/private/itemDomainInventoryListObject.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/list.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignCreateMDInventoryDialog.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewDetailsPanel.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewTreeList.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/machineDesignContextMenu/addMachineDesignContextMenuItem.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/machineDesignContextMenu/addMachineDesignSubMenu.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/machineDesignContextMenu/cableSubMenu.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/machineDesignContextMenu/detachFromHierarchyContextMenuItem.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/subAssembly.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/view.xhtml
> Add initial support for machine design inventory. 

- README.md
Added unzip commands to the prereq installs.  Was unable to install glassfish, etc. without this.
> added unzip commands to the prereq installs

- .gitignore
- setup.sh
- tools/developer_tools/python-client/CdbApiFactory.py
- tools/developer_tools/python-client/cdbCli/common/cli/cliBase.py
- tools/developer_tools/python-client/cdbCli/common/utility/configurationManager.py
- tools/developer_tools/python-client/cdbCli/service/cli/addLogToItemByIdCli.py
- tools/developer_tools/python-client/cdbCli/service/cli/getItemByIdCli.py
- tools/developer_tools/python-client/generatePyClient.sh
> Create a basic framework for CLI development

- support/bin/install_netbeans.sh
@iTerminate, 
Netbeans link was down, this request has the up-to-date link. 
Thanks,
@jeonghanlee
> fixed the broken netbean link

- src/java/CdbWebPortal/web/views/itemDomainCableCatalog/view.xhtml
- src/java/CdbWebPortal/web/views/itemDomainCableInventory/view.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerDomainCableCatalogController.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerDomainCableInventoryController.java
- tools/developer_tools/cdb_plugins/plugins/traveler/java/ItemTravelerDomainInstanceControllerBase.java
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/itemDetailsViewSections/cableCatalogSections.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/itemDetailsViewSections/cableInventorySections.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerInstanceListActionObject.xhtml
- tools/developer_tools/cdb_plugins/plugins/traveler/xhtml/support/travelerInstanceMoveDialog.xhtml
- tools/developer_tools/cdb_plugins/utilities/plugin_xhtml_parser.py
> add traveler plugin for cable catalog and inventory

- src/java/CdbWebPortal/src/java/gov/anl/aps/cdb/portal/controllers/ItemDomainMachineDesignController.java
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewTreeContextMenu.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/itemDomainMachineDesignDualColumnListViewTreeContextMenuSupport.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/machineDesignContextMenu/deleteHierarchyMachineDesignContextMenuItem.xhtml
- src/java/CdbWebPortal/web/views/itemDomainMachineDesign/private/machineDesignContextMenu/destroyMachineDesignContextMenuItem.xhtml
- tools/developer_tools/utilities/cable_import/preImport.py
Finish delete hierarchy and disable for upcoming release.
> merge latest from my fork

- tools/developer_tools/python-client/CdbApiFactory.py
- tools/developer_tools/python-client/cdbCli/common/cli/cliBase.py
- tools/developer_tools/python-client/cdbCli/common/utility/configurationManager.py
Some simple bug fixes for cdbCli.
> Bug Fixes For cdbCli

- tools/developer_tools/python-client/cdbCli/service/cli/cdbCliCmnds/getProperties.py
- tools/developer_tools/python-client/cdbCli/service/cli/cdbCliCmnds/setPropertiesAndMetadata.py
Updated the setPropertiesAndMetadata module to take a command line switch that will remove the property.
> Updated cdbcli set properties module to allow property deletion.
